-- Hard drop and recreate all problematic policies exactly as named in the linter
DROP POLICY IF EXISTS "Allow all" ON public."categories";
CREATE POLICY "Allow all" ON public."categories" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "Allow all on categories" ON public."categories";
CREATE POLICY "Allow all on categories" ON public."categories" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "donations_all" ON public."donations";
CREATE POLICY "donations_all" ON public."donations" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "eco_log_all" ON public."ecosystem_log";
CREATE POLICY "eco_log_all" ON public."ecosystem_log" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "Allow all" ON public."events";
CREATE POLICY "Allow all" ON public."events" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "gallery_all" ON public."gallery_images";
CREATE POLICY "gallery_all" ON public."gallery_images" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "Allow all" ON public."judge_agreements";
CREATE POLICY "Allow all" ON public."judge_agreements" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "Allow all on judge_agreements" ON public."judge_agreements";
CREATE POLICY "Allow all on judge_agreements" ON public."judge_agreements" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "judge_agreements_all" ON public."judge_agreements";
CREATE POLICY "judge_agreements_all" ON public."judge_agreements" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "Allow all" ON public."judge_credentials";
CREATE POLICY "Allow all" ON public."judge_credentials" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "judge_insert" ON public."judge_credentials";
CREATE POLICY "judge_insert" ON public."judge_credentials" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "judge_update" ON public."judge_credentials";
CREATE POLICY "judge_update" ON public."judge_credentials" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "Allow all" ON public."knsdc-registration";
CREATE POLICY "Allow all" ON public."knsdc-registration" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "notices_all" ON public."notices";
CREATE POLICY "notices_all" ON public."notices" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "partners_all" ON public."partners";
CREATE POLICY "partners_all" ON public."partners" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "Allow all" ON public."public_messages";
CREATE POLICY "Allow all" ON public."public_messages" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "Allow all on public_messages" ON public."public_messages";
CREATE POLICY "Allow all on public_messages" ON public."public_messages" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "Allow all" ON public."public_ratings";
CREATE POLICY "Allow all" ON public."public_ratings" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "Allow all on public_ratings" ON public."public_ratings";
CREATE POLICY "Allow all on public_ratings" ON public."public_ratings" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "Allow all" ON public."public_registrations";
CREATE POLICY "Allow all" ON public."public_registrations" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "Allow all" ON public."scoring_subjects";
CREATE POLICY "Allow all" ON public."scoring_subjects" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "subjects_manage" ON public."scoring_subjects";
CREATE POLICY "subjects_manage" ON public."scoring_subjects" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "Allow all" ON public."staff_credentials";
CREATE POLICY "Allow all" ON public."staff_credentials" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "staff_insert" ON public."staff_credentials";
CREATE POLICY "staff_insert" ON public."staff_credentials" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "staff_update" ON public."staff_credentials";
CREATE POLICY "staff_update" ON public."staff_credentials" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "Allow all" ON public."sync_state";
CREATE POLICY "Allow all" ON public."sync_state" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "sync_state_insert" ON public."sync_state";
CREATE POLICY "sync_state_insert" ON public."sync_state" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "sync_state_update" ON public."sync_state";
CREATE POLICY "sync_state_update" ON public."sync_state" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "team_all" ON public."team_members";
CREATE POLICY "team_all" ON public."team_members" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "Allow all" ON public."venues";
CREATE POLICY "Allow all" ON public."venues" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "Allow all on venues" ON public."venues";
CREATE POLICY "Allow all on venues" ON public."venues" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "work_items_all" ON public."work_items";
CREATE POLICY "work_items_all" ON public."work_items" FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);