name = "sb2"
main = "cloudflare-r2-worker.js"
compatibility_date = "2024-09-01"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "my-app-uploads"

[vars]
PUBLIC_URL = "https://pub-407c9d11c2a04dc1973e0dc94d659214.r2.dev"
